language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - RUST_BACKTRACE=1 PATH="$HOME/.cargo/bin:$PATH"
script:
  - cargo test
  - cargo run -- --deadbeef deadbeef.o
  - cargo run -- --link test test.o deadbeef.o
  - ./test
