[package]
name = "faerie"
version = "0.4.3"
authors = ["m4b <m4b.github.io@gmail.com>", "Dan Gohman <sunfish@mozilla.com>", "Pat Hickey <pat@moreproductive.org>"]
readme = "README.md"
keywords = ["elf", "mach-o", "binary", "object", "compiler"]
repository = "https://github.com/m4b/faerie"
license = "MIT"
description = "ELF and Mach-o native binary object file emitter"
documentation = "https://docs.rs/faerie"
categories = ["development-tools::debugging"]
include = ["src/**/*", "Cargo.toml", "LICENSE", "README.md", "tests/*"]

[[bin]]
name = "prototype"
path = "src/bin/main.rs"

[dependencies]
goblin = "0.0.14"
scroll = "0.8.0"
log = "0.4.3"
env_logger = "0.5.10"
indexmap = "1.0.1"
structopt = "0.2.10"
structopt-derive = "0.2.10"
string-interner = "0.6.3"
failure = "0.1.1"
target-lexicon = "0.0.3"
