[package]
name = "faerie"
version = "0.1.0"
authors = ["m4b <m4b.github.io@gmail.com>"]
readme = "README.md"
keywords = ["elf", "mach-o", "binary", "object", "compiler"]
repository = "https://github.com/m4b/faerie"
license = "MIT"
description = "ELF and Mach-o native binary object file emitter"
documentation = "https://docs.rs/faerie"
categories = ["development-tools::debugging"]
include = ["src/**/*", "Cargo.toml", "LICENSE", "README.md", "tests/*"]

[[bin]]
name = "prototype"
path = "src/bin/main.rs"

[dependencies]
goblin = "0.0.14"
scroll = "0.8"
log = "0.4.1"
env_logger = "0.5.8"
indexmap = "1.0.0"
structopt = "0.2.3"
structopt-derive = "0.2.3"
string-interner = "0.6.3"
failure = "0.1.1"
